---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ m3_coordinator_service_name }}'
    consul_services:
      - name: '{{ m3_coordinator_service_name }}'
        tags: ['monitor', 'metrics-store']
        addr: '{{ ansible_local.tinc.vpn_ip }}'
        port: '{{ m3_coordinator_query_port }}'
        checks:
          - id: '{{ m3_coordinator_service_name }}-health'
            name: M3 Coordinator health
            type: http
            http: 'http://localhost:{{ m3_coordinator_query_port }}/health'
