---
- name: M3 Coordinator | Get ETCD cluster nodes
  uri:
    url: '{{ consul_catalog_url }}/service/{{ m3_coordinator_etcd_service_name }}'
  register: m3_coordinator_etcd_services

- name: M3 Coordinator | Assemble ETCD endrpoints
  set_fact:
    m3_coordinator_etcd_endpoints: '{{ m3_coordinator_etcd_services.json | json_query( "[].[to_string(ServiceAddress), to_string(ServicePort)]") | map("join", ":") | list }}'
